bookshop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^cart/',include('cart.urls',namespace="cart")),
	url(r'^orders/',include('order.urls',namespace='order')),
	url(r'^paypal/', include('paypal.standard.ipn.urls')),
	url(r'^payment/',include('payment.urls',namespace='payment')),
	url(r'^coupons/', include('coupons.urls', namespace='coupons')),
	url(r'',include('shop.urls',namespace="shop")),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name="cart"
urlpatterns = [
    url(r'^$',views.cart_detail,name="cart_detail"),
    url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name="cart_add"),
    url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name="cart_remove"),
]

coupons/urls.py
from django.conf.urls import url
from . import views

app_name = 'coupons'
urlpatterns = [
    url(r'^apply/$',views.coupon_apply,name='apply'),
]

order/urls.py
from django.conf.urls import url
from . import views

app_name = 'order'
urlpatterns = [
    url(r'^create/',views.order_create,name='order_create'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$',views.admin_order_pdf,name='admin_order_pdf'),
    url(r'^admin/order/(?P<order_id>\d+)/$',views.admin_order_detail,name='admin_order_detail'),
]

shop/urls.py
from django.conf.urls import url
from . import views

app_name="shop"
urlpatterns = [
    url(r'^$',views.indexView,name="index"),
    url(r'^list/(?P<categoryid>\d+)/$',views.indexView,name="book_list_by_category"),
    url(r'^detail/(?P<id>\d+)/$',views.book_detail,name="book_detail"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):

    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                       coerce=int)
    update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Book
from .cart import  Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm

# Create your views here.

@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    book = get_object_or_404(Book,id = product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=book,quantity=cd['quantity'],update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request,product_id):
    cart = Cart(request)
    book = get_object_or_404(Book,id = product_id)
    cart.remove(book)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'],'update':True})
    coupon_apply_form = CouponApplyForm()
    return render(request,'cart/detail.html',{'cart':cart,'coupon_apply_form':coupon_apply_form})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	shoping cart
{% endblock %}

{% block content %}
	<h1>Your shopping cart</h1>
	<table style="float:right;padding-top:4px;">
		<thead>
			<tr>
				<th>Image</th>
				<th>Product</th>
				<th>Quantity</th>
				<th>Remove</th>
				<th>Unit price</th>
				<th>Price</th>
			</tr>
		</thead>
		<tbody>
			{% for item in cart %}
				{% with product=item.product %}
					<tr>
						<td>
							<a href="{{ product.get_absolute_url }}">
								<img src="{{ product.cover.url }}" class="img-responsive">
							</a>
						</td>
						<td>
							{{ product.title }}
						</td>
						<td>
							<form action="{% url 'cart:cart_add' product.id %}" method="post">
								{{ item.update_quantity_form.quantity }}
								{{item.update_quantity_form.update}}
								<input type="submit" name="" value="update">
								{% csrf_token %}
							</form>
						</td>
						<td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
						<td style="text-align: right;">￥{{ item.price }}</td>
						<td style="text-align: right;">￥{{ item.total_price }}</td>
					</tr>
				{% endwith %}
			{% endfor %}
			{% if cart.coupon %}
				<tr class="subtotal">
				<td>Subtotal</td>
				<td colspan="4"></td>
				<td class="num">${{ cart.get_total_price }}</td>
				</tr>
				<tr>
				<td>
				"{{ cart.coupon.code }}" coupon
				({{ cart.coupon.discount }}% off)
				</td>
				<td colspan="4"></td>
				<td class="num neg">
				- ${{ cart.get_discount|floatformat:"2" }}
				</td>
				</tr>
				{% endif %}
				<tr class="total">
				<td>Total</td>
				<td colspan="4"></td>
				<td class="num">
					${{ cart.get_total_price_after_discount|floatformat:"2" }}
				</td>
				</tr>
		</tbody>
	</table>
	<p>Apply a coupon:</p>
		<form action="{% url "coupons:apply" %}" method="post">
		{{ coupon_apply_form }}
		<input type="submit" value="Apply">
		{% csrf_token %}
		</form>
	<p style="text-align: right;">
		<a href="{% url 'shop:index' %}">Continue shopping</a>
		<a href="{% url 'order:order_create' %}"><button type="button" >Checkout</button></a>
	</p>
{% endblock %}