bookshop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^cart/',include('cart.urls',namespace="cart")),
	url(r'^orders/',include('order.urls',namespace='order')),
	url(r'^paypal/', include('paypal.standard.ipn.urls')),
	url(r'^payment/',include('payment.urls',namespace='payment')),
	url(r'^coupons/', include('coupons.urls', namespace='coupons')),
	url(r'',include('shop.urls',namespace="shop")),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name="cart"
urlpatterns = [
    url(r'^$',views.cart_detail,name="cart_detail"),
    url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name="cart_add"),
    url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name="cart_remove"),
]

shop/urls.py
from django.conf.urls import url
from . import views

app_name="shop"
urlpatterns = [
    url(r'^$',views.indexView,name="index"),
    url(r'^list/(?P<categoryid>\d+)/$',views.indexView,name="book_list_by_category"),
    url(r'^detail/(?P<id>\d+)/$',views.book_detail,name="book_detail"),
]

shop/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MaxLengthValidator,MinLengthValidator
from django.core.exceptions import ValidationError
from django.urls import reverse
import datetime


# Create your models here.


class Category(models.Model):
	name = models.CharField(_('Category'),max_length=64)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = _('Category')
		verbose_name_plural = _('Category')

	def get_absolute_url(self):
		return reverse('shop:book_list_by_category',args=[str(self.id)])


		

today_str 	= "({} {})".format(_(".etc"),datetime.datetime.now().strftime("%Y-%m-%d"))


class BookEditValidator(object):
	@staticmethod
	def isdigit(value):
		if not value.isdigit():
			raise ValidationError(_('%s not pure digits') % value)


class Book(models.Model):

	#isbn10		= models.CharField(_('ISBN10'),default="",max_length=10,blank=True)
	isbn13		= models.CharField(_('ISBN13'),max_length=13,validators=[BookEditValidator.isdigit,MaxLengthValidator(13),MinLengthValidator(13)])
	title		= models.CharField(_('Title'),max_length=128)
	subtitle 	= models.CharField(_('Subtitle'),max_length=128,default="",blank=True)
	pages		= models.PositiveSmallIntegerField(_('Pages'),default=0,blank=0,null=0)
	author		= models.CharField(_('Author'),max_length=256,default="",blank=True)
	translator	= models.CharField(_('Translator'),max_length=256,default="",blank=True)
	publisher	= models.CharField(_('Publisher'),max_length=256,default="",blank=True)
	price		= models.DecimalField(_('Price'),max_digits=5,decimal_places=2,default=0,blank=True,null=True)
	binding		= models.CharField(_('Binding'),max_length=128,default="",blank=True)
	pubdate		= models.DateField(_('Date Published'),blank=True,null=True,help_text=today_str)
	authorDesc	= models.TextField(_('Author Desc'),blank=True,default="")
	cover		= models.ImageField(_('Book Cover'),upload_to="face/%Y/%m/%d",default="defa/1.jpg")
	summary		= models.TextField(_('Summary'),blank=True,default="")
	rating		= models.DecimalField(_('Rating'),max_digits=5,decimal_places=2,default=0,blank=True,null=True)
	category	= models.ForeignKey(Category,on_delete=models.SET_NULL,default="",blank=True,null=True,verbose_name=_('Category'))
	stock		= models.PositiveSmallIntegerField(_('Stock'),default=0,blank=True,null=True)
	sale		= models.BooleanField(_('Sale'),default=True,blank=True)
	douban		= models.URLField(_('douban'),max_length=255,default="",blank=True)
	#readPages	= models.PositiveSmallIntegerField(_('Read Pages'),default=0,blank=0,null=0,help_text="(%s)" %(_("Pages Be Read")))
	#readStart	= models.DateField(_('Reading Start'),blank=True,null=True,help_text=today_str)
	#readEnd		= models.DateField(_('Reading Finished'),blank=True,null=True,help_text=today_str)
	#readTags	= models.TextField(_('Reading Tags'),default="",blank=True)
	#readNote	= models.TextField(_('Reading Note'),default="",blank=True)
	#boughtPrice	= models.DecimalField(_('Price Bought'),max_digits=5,decimal_places=2,default=0,blank=True,null=True)
	#boughtDate 	= models.DateField(_('Date Bought'),blank=True,null=True,help_text=today_str)
	#location	= models.ForeignKey(Location,default="",blank=True,null=True,verbose_name=_('Location')) 
	def __str__(self):
		return self.title

	class Meta:
		verbose_name = _("Book")
		verbose_name_plural =verbose_name

	def get_absolute_url(self):

		return reverse('shop:book_detail',args=[str(self.id)])

shop/views.py
from django.shortcuts import render,get_object_or_404
from .models import Book,Category
from cart.forms import CartAddProductForm
# Create your views here.

def indexView(request,categoryid = None):
    category = None
    categories = Category.objects.all()
    booklist = Book.objects.filter(sale=True)
    if categoryid:
        category = get_object_or_404(Category,id=categoryid)
        booklist = booklist.filter(category=category)
    return render(request,'shop/index.html',{'booklist':booklist,
                                             'category':category,
                                             'categories':categories})

def book_detail(request,id):
    book = get_object_or_404(Book,id=id,sale=True)
    cart_product_form = CartAddProductForm()
    return render(request,'shop/detail.html',{'book':book,
                                              'cart_product_form':cart_product_form})

shop/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>
        {% block title %}
            HOME
        {% endblock %}
    </title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/customize.css' %}" rel="stylesheet">

</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Bookshop</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">BookShop</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'shop:index' %}">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                  <a href="{% url 'cart:cart_detail' %}">{{ total_items }} item{{ total_items|pluralize}},￥{{ cart.get_total_price }}</a>
                {% else %}
                Your cart is empty
                {% endif %}
              {% endwith %}
            </li>
            <li><a href="#">Static top</a></li>
            <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <div class="row">
            {% block content%}
            {% endblock %}
        </div>
    </div>



<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>